wikistats/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^views/', include('wikiviews.urls')),
]

wikiviews/urls.py
from django.conf.urls import url, include
from . import views, views_plot, views_ajax

app_name="wikiviews"
urlpatterns = [
    url(r'^corr/?',                 views.correlation_view,     name="correlation"),
    url(r'^plot/?',                 views_plot.correlation_plot_view, name="correlation_plot"),

    url(r'^autocomplete/?',         views.autocomplete_json,    name="autocomplete"),
    url(r'^ajax/list/?',            views_ajax.views_list, name="views_list"),
]

wikiviews/models.py
# coding=utf-8
from __future__ import unicode_literals

import datetime

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.validators import validate_comma_separated_integer_list
from django.urls import reverse

from picklefield import PickledObjectField


class WikiTerm(models.Model):

    name = models.CharField(verbose_name=_("name"), max_length=128)
    url = models.URLField(verbose_name=_("url"))
    description = models.TextField(verbose_name=_("description"))

    def page_name(self):
        return self.url.split("/wiki/")[1]

    def __unicode__(self):
        return self.name


class WikiPageviews(models.Model):

    term = models.ForeignKey(verbose_name=_("term"), to=WikiTerm)
    year = models.IntegerField(verbose_name=_("year"))
    project = models.CharField(verbose_name=_("project/site"), max_length=30)
    agent = models.CharField(verbose_name=_("agent"), max_length=10)
    access = models.CharField(verbose_name=_("access"), max_length=10)

    count = models.IntegerField(verbose_name=_("count"))
    per_yearday = models.CharField(verbose_name=_("per year-day"), max_length=4096,
                                   validators=[validate_comma_separated_integer_list])

    def correlation_url(self):
        return "%s?article=%s" % (reverse("wikiviews:corr"), self.term.name)

    def views_per_day(self):
        return [int(x) for x in self.per_yearday.split(",")]

    def views_decorator(self, transform=None):
        import numpy as np
        views = self.views_per_day()
        if transform is not None:
            views = transform(views)
        NUM_DAYS = 3 if len(views) > 180 else 1
        views_av = [0] * ((len(views)+NUM_DAYS-1) // NUM_DAYS)
        for i, v in enumerate(views):
            views_av[i//NUM_DAYS] += v
        min_views, max_views = min(views_av), max(views_av)
        if min_views > 0:
            min_views = min_views * 2 // 3
        max_views = max(min_views+1, max_views)
        html = '<div class="histogram">'
        start_ord = datetime.date(self.year, 1, 1).toordinal()
        for i, v in enumerate(views_av):
            title = "%s views between %s and %s" % (
                v,
                datetime.date.fromordinal(start_ord + i*NUM_DAYS),
                datetime.date.fromordinal(start_ord + (i+1)*NUM_DAYS-1),
            )
            html += '<span class="histogram-bin" title="%s">' % title
            html += '<span class="histogram-value" style="height: %s%%;">' % round(
                        100. - (float(v) - min_views) / (max_views - min_views) * 100., 1)
            html += '</span></span>'
        html += '</div>'
        return html
    views_decorator.short_description = _("views")
    views_decorator.allow_tags = True


class PickleCache(models.Model):
    """Cache for picklable data"""

    id = models.CharField(max_length=100, verbose_name=_("id"), unique=True, primary_key=True)
    created = models.DateTimeField(verbose_name=_("created on"), auto_now=True)
    data = PickledObjectField(verbose_name=_("headers"), default=None, blank=True, null=True)

    @classmethod
    def clear(cls, id):
        qset = cls.objects.filter(id=id)
        if qset.exists():
            qset.delete()
            return True
        return False

    @classmethod
    def clear_like(cls, id):
        qset = cls.objects.filter(id__icontains=id)
        if qset.exists():
            qset.delete()
            return True
        return False

    @classmethod
    def store(cls, id, data):
        try:
            o = cls.objects.get(id=id)
            o.created = datetime.datetime.now()
            o.data = data
            o.save()
        except cls.DoesNotExist:
            cls.objects.create(
                id=id,
                data=data
            )

    @classmethod
    def restore(cls, id):
        try:
            o = cls.objects.get(id=id)
            return o.data
        except cls.DoesNotExist:
            return None

wikiviews/views.py
# coding=utf-8
from __future__ import unicode_literals, print_function

import numpy as np
import scipy

from django.shortcuts import render
from django.http import JsonResponse, Http404

from .models import *
from tools.opensearch import opensearch_and_store
from tools.pageviews import get_pageviews_and_store


def autocomplete_json(request):
    query = request.GET.get("q")
    if not query:
        raise Http404

    if "w" in request.GET:
        res = opensearch_and_store(query, limit=100)
        return JsonResponse({
            "items": [i["name"] for i in res[:20]]
        })

    qset = WikiPageviews.objects.filter(term__name__icontains=query)
    items = qset.order_by("term__name").values_list("term__name")
    items = [t[0] for t in items[:20]]
    return JsonResponse({
        "items": items
    })



def correlation_view(request):
    def _normalize(a):
        m = np.linalg.norm(a)
        if m:
            return a / m
        return a

    WEEKDAYS = [datetime.date.fromordinal(datetime.date(2016, 1, 1).toordinal()+i).weekday() for i in range(366)]
    def _weekday(a):
        r = np.zeros(7)
        for i, v in enumerate(a):
            r[WEEKDAYS[i]] += v
        return r

    TRANSFORMS = (
        ("", "none", None),
        ("grad", "np.gradient", lambda a: np.gradient(a)),
        ("diff", "np.diff", lambda a: np.diff(a)),
        ("fft", "np.fft", lambda a: np.real(np.fft.fft(a))[2:len(a)//2+1]),
        ("clip", "clip mean+std", lambda a: np.clip(a, 0, np.mean(a)+np.std(a))),
        ("weekday", "weekday", lambda a: _weekday(a))
    )
    COMPARISONS = (
        ("corr", "correlation",
            lambda x, y: np.corrcoef(x, y)[0][1],
            lambda v: v <= -.3 or v >= .5,
            lambda v: -v,
        ),
        ("ndist", "norm distance",
            lambda x, y: np.linalg.norm(x-y) / np.sum(np.abs(x-y)),
            lambda v: v < .5,
            lambda v: v,
        ),
    )

    art_name = request.GET.get("article")
    transform_name = request.GET.get("transform", "")
    compare_name = request.GET.get("compare", "corr")

    transform = None
    if transform_name:
        trans = sorted(TRANSFORMS, key=lambda x: x[0] == transform_name)[-1]
        transform = trans[2]

    compr = sorted(COMPARISONS, key=lambda x: x[0] == compare_name)[-1]


    term = None
    correlations = []
    qset = WikiPageviews.objects.filter(term__name=art_name)

    # try to retrieve pageviews
    if not qset.exists():
        qset = WikiTerm.objects.filter(name=art_name)
        if qset.exists():
            get_pageviews_and_store(2016, qset[0])

    def _get_array(views):
        a = views.views_per_day()
        if transform is not None:
            a = transform(a)
        else:
            a = np.array(a, dtype="float64")
        return a

    qset = WikiPageviews.objects.filter(term__name=art_name)
    if qset.exists():

        base_views = qset[0]
        term = base_views.term
        base_array = _get_array(base_views)

        qset = WikiPageviews.objects.all()
        for view in qset:
            comp_array = _get_array(view)
            corr = compr[2](base_array, comp_array)
            if compr[3](corr):
                correlations.append({
                    "name": view.term.name,
                    "desc": view.term.description,
                    "url": view.term.url,
                    "corr_url": "?article=%s&transform=%s" % (view.term.name, transform_name),
                    "count": view.count,
                    "correlation": round(corr, 3),
                    "views_decorator": view.views_decorator(transform=transform),
                })

    ctx = {
        "term": term,
        "correlations": sorted(correlations, key=lambda c: compr[4](c["correlation"]))[:100],
        "transforms": TRANSFORMS,
        "comparisons": COMPARISONS,
        "current_transform": transform_name,
        "current_compare": compare_name,
        "current_compare_name": compr[1],
    }
    return render(request, "wikiviews/correlations.html", ctx)

wikiviews/templates/wikiviews/base.html
<!doctype html
    PUBLIC "-//W3C//DTD HTML 4.01//EN"
    "http://www.w3.org/TR/html4/strict.dtd">
{% load static %}
<html>
    <head profile="http://www.w3.org/2005/10/profile">
        <meta charset="utf-8">
        {% if page_title %}
            <title>{{ page_title }}</title>
        {% endif %}
        <link href="{% static 'wikiviews/jquery-ui.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'wikiviews/bokeh-0.12.4.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'wikiviews/stylesheet.css' %}" rel="stylesheet" type="text/css" />
        <script type="text/javascript" src="{% static 'wikiviews/bokeh-0.12.4.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'wikiviews/jquery-3.1.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'wikiviews/jquery-ui.min.js' %}"></script>
        {% for c in css %}
            <link href="{% static c %}" rel="stylesheet" type="text/css" />
        {% endfor %}
        {% for c in js %}
            <script src="{% static c %}"></script>
        {% endfor %}
    </head>

    <body>
        <div class="page-content">

            {% if developer %}
                <div class="developer">{{ developer|safe }}</div>
            {% endif %}

            {% if help %}
                <p class="help-button button">help</p>
                <div class="help-container"><hr/>{{ help|safe }}</div>
                <hr/>
            {% endif %}

            {% if error %}
            <div class="error">{{ error|safe }}</div>
            {% endif %}

            {% block content %}
                {{ content|safe }}
            {% endblock %}
        </div>

        {% if help %}
        <script type="text/javascript">
            $(function() {
                $(".help-container").hide();
                $(".help-button").click(function(event) {
                    $(".help-container").toggle("slow");
                });
            });
        </script>
        {% endif %}
    </body>
</html>

wikiviews/templates/wikiviews/correlations.html
{% extends './base.html' %}

{% block content %}


<form>
    <label for="article-input">article to compare</label>
    <input type="text" id="article-input" name="article" value="{{ term.name }}" />
    <input type="submit" value="go" />
    <br/>
    <label for="cb-transform">transform: </label>
    <select id="cb-transform" name="transform">
        {% for t in transforms %}
            <option value="{{t.0}}" {% if current_transform == t.0 %}selected{% endif %}>{{ t.1 }}</option>
        {% endfor %}
    </select>

    <label for="cb-compare">compare by: </label>
    <select id="cb-compare" name="compare">
        {% for t in comparisons %}
            <option value="{{t.0}}" {% if current_compare == t.0 %}selected{% endif %}>{{ t.1 }}</option>
        {% endfor %}
    </select>
</form>

<hr/>

<table class="result-table">
    <thead>
        <tr>
            <td>article</td>
            <td>views per year</td>
            <td>{{ current_compare_name }}</td>
            <td>views</td>
        </tr>
    </thead>
    {% for a in correlations %}
    <tr>
        <td style="max-width: 270px">
            (<a href="{{ a.url }}" target="_blank" title="{{ a.desc }}">W</a>)
            (<a href="{{ a.corr_url }}" title="correlate from here">C</a>)
            {{ a.name }}
        </td>
        <td class="number">{{ a.count }}</td>
        <td class="number">{{ a.correlation }}</td>
        <!--<td><a href="{{ a.url }}" target="_blank">{{ a.url }}</a></td>-->
        <td>{{ a.views_decorator|safe }}</td>
    </tr>
    {% endfor %}
</table>



<script>
    $(function() {
        $("input#article-input").autocomplete({
            delay: 200,
            minLength: 2,
            source: function(request, response) {
                $.ajax({
                    url: "{% url 'wikiviews:autocomplete' %}",
                    data: {
                        q: request.term
                    },
                    success: function(data) {
                        if (data.items)
                            response(data.items);
                    }
                });
            }
        });
    });
</script>

{% endblock %}

wikiviews/templates/wikiviews/views-list.html
<table class="result-table">
    <thead>
        <tr>
            <td>article</td>
            <td>views per year</td>
            <td>views</td>
        </tr>
    </thead>
    {% for v in views %}
    <tr>
        <td style="max-width: 270px">
            (<a href="{{ v.term.url }}" target="_blank" title="{{ v.term.description }}">W</a>)
            (<a href="{{ v.corr_url }}" title="correlate from here">C</a>)
            {{ v.term.name }}
        </td>
        <td class="number">{{ v.count }}</td>
        <!--<td><a href="{{ a.url }}" target="_blank">{{ a.url }}</a></td>-->
        <td>{{ v.views_decorator|safe }}</td>
    </tr>
    {% endfor %}
</table>